apiVersion: v1
kind: Service
metadata:
  name: yobot-service
  namespace: default
spec:
  selector:
    app: yobot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
